apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kusoge-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Houeta/kusoge-xasc.git
    path: helm/kusoge
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true