{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Chart.Name }}-external-secret"
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook-weight": "-10"
    "helm.sh/resource-policy": delete
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: "{{ .Chart.Name }}-aws-parameter-store"
    kind: ClusterSecretStore
  target:
    name: "secret-store"
    creationPolicy: Owner
  data:
  {{- range $v := .Values.secrets.keyRef }}
  - secretKey: {{ $v.secretKey }}
    remoteRef:
      key: {{ $v.awsKey }}
  {{- end }}
{{- end }}