---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Name }}-db-headless"
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: "{{ .Chart.Name }}-{{ .Release.Name }}-db"
  ports:
  - port: {{ .Values.db.port }}
    targetPort: {{ .Values.db.targetPort | default .Values.db.port }}