{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "{{ .Chart.Name }}-aws-parameter-store"
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.secrets.ss_region }}
      auth:
        jwt:
          serviseAccountRef:
            name: es-service-account
            namespace: external-secrets
{{- end }}