name: Update Container Image

on:
  workflow_dispatch:
    inputs:
      message:
        required: true
        description: A message describing why this workflow is being invoked
      sha:
        required: true
        description: The short hash of the commit the invoked this workflow
      image_repo:
        required: true
        description: The new image repo
      image_tag:
        required: true
        description: The new image tag
      helm_name:
        required: true
        description: Service name in helmchart

env:
  HELM_PATH: helm/kusoge
  IMAGE_NAME: "${{ github.event.inputs.image_repo }}:${{github.event.inputs.image_tag}}"

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Print new image value
      run: echo "New image is ${{ env.IMAGE_NAME }}"
    
    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq
    
    - name: Update values.yaml
      run: |
        'yq -i e ".${{github.event.inputs.helm_name}}.image.repository = \"${{ github.event.inputs.image_repo }}\"" ${{ env.HELM_PATH }}/values.yaml'
        'yq -i e ".${{github.event.inputs.helm_name}}.image.tag = \"${{ github.event.inputs.image_tag }}\"" ${{ env.HELM_PATH }}/values.yaml'
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      id: cpr
      with:
        title: ${{github.event.inputs.message}}
        branch: update-image-${{ github.event.inputs.sha }}
        commit-message: update backend image tag to ${{ env.IMAGE_NAME }}
    
    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"